# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/authn-service"
    schedule:
      interval: "daily"
    labels:
      - "triage-required"
    assignees:
      - "joshjohanning"
    reviewers:
      - "joshjohanning"
    commit-message:
      prefix: "pip"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    labels:
      - "triage-required"
    assignees:
      - "joshjohanning"
    reviewers:
      - "joshjohanning"
    commit-message:
      prefix: "npm"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "triage-required"
    assignees:
      - "joshjohanning"
    reviewers:
      - "joshjohanning"
    commit-message:
      prefix: "github-actions"
